# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    url: jdbc:mysql://guhm.vicp.cc:63306/wechat_service
    username: wechat
    password: Wechat@123456
  jpa:
    datebase: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        max-wait: -1ms
        min-idle: 5
    password:
    port: 6379
    timeout: 6000ms
wcs:
  wxqy:
    corpid: test
    secret: test
    agentid: test
